<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Bidders.php');
	include_once(__DIR__ . '/Bidders_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Bidders');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Bidders';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Bidders`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`Contacts1`.`MailingNameFull`), CONCAT_WS('',   `Contacts1`.`MailingNameFull`), '') /* Contact */" => "ContactID",
		"`Bidders`.`BidNo`" => "BidNo",
		"`Bidders`.`BidderType`" => "BidderType",
		"`Bidders`.`CheckedIn`" => "CheckedIn",
		"`Bidders`.`QuickPay`" => "QuickPay",
		"`Bidders`.`TotalBids`" => "TotalBids",
		"`Bidders`.`TotalOwed`" => "TotalOwed",
		"IF(    CHAR_LENGTH(`Contacts1`.`MailingNameFull`), CONCAT_WS('',   `Contacts1`.`MailingNameFull`), '') /* MailingName */" => "MailingName",
		"`Bidders`.`TablePreference`" => "TablePreference",
		"`Bidders`.`Card`" => "Card",
		"`Bidders`.`TotalPaid`" => "TotalPaid",
		"IF(    CHAR_LENGTH(`Contacts1`.`Business`), CONCAT_WS('',   `Contacts1`.`Business`), '') /* Business Name */" => "Business",
		"IF(    CHAR_LENGTH(`Contacts1`.`Address1`), CONCAT_WS('',   `Contacts1`.`Address1`), '') /* Address1 */" => "Address1",
		"IF(    CHAR_LENGTH(`Contacts1`.`Address2`), CONCAT_WS('',   `Contacts1`.`Address2`), '') /* Address2 */" => "Address2",
		"IF(    CHAR_LENGTH(`Contacts1`.`City`), CONCAT_WS('',   `Contacts1`.`City`), '') /* City */" => "City",
		"IF(    CHAR_LENGTH(`Contacts1`.`State`), CONCAT_WS('',   `Contacts1`.`State`), '') /* State */" => "State",
		"IF(    CHAR_LENGTH(`Contacts1`.`Zip`), CONCAT_WS('',   `Contacts1`.`Zip`), '') /* Zip */" => "Zip",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Bidders`.`ID`',
		2 => '`Contacts1`.`MailingNameFull`',
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`Bidders`.`TotalBids`',
		8 => '`Bidders`.`TotalOwed`',
		9 => '`Contacts1`.`MailingNameFull`',
		10 => 10,
		11 => 11,
		12 => '`Bidders`.`TotalPaid`',
		13 => '`Contacts1`.`Business`',
		14 => '`Contacts1`.`Address1`',
		15 => '`Contacts1`.`Address2`',
		16 => '`Contacts1`.`City`',
		17 => '`Contacts1`.`State`',
		18 => '`Contacts1`.`Zip`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Bidders`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`Contacts1`.`MailingNameFull`), CONCAT_WS('',   `Contacts1`.`MailingNameFull`), '') /* Contact */" => "ContactID",
		"`Bidders`.`BidNo`" => "BidNo",
		"`Bidders`.`BidderType`" => "BidderType",
		"`Bidders`.`CheckedIn`" => "CheckedIn",
		"`Bidders`.`QuickPay`" => "QuickPay",
		"`Bidders`.`TotalBids`" => "TotalBids",
		"`Bidders`.`TotalOwed`" => "TotalOwed",
		"IF(    CHAR_LENGTH(`Contacts1`.`MailingNameFull`), CONCAT_WS('',   `Contacts1`.`MailingNameFull`), '') /* MailingName */" => "MailingName",
		"`Bidders`.`TablePreference`" => "TablePreference",
		"`Bidders`.`Card`" => "Card",
		"`Bidders`.`TotalPaid`" => "TotalPaid",
		"IF(    CHAR_LENGTH(`Contacts1`.`Business`), CONCAT_WS('',   `Contacts1`.`Business`), '') /* Business Name */" => "Business",
		"IF(    CHAR_LENGTH(`Contacts1`.`Address1`), CONCAT_WS('',   `Contacts1`.`Address1`), '') /* Address1 */" => "Address1",
		"IF(    CHAR_LENGTH(`Contacts1`.`Address2`), CONCAT_WS('',   `Contacts1`.`Address2`), '') /* Address2 */" => "Address2",
		"IF(    CHAR_LENGTH(`Contacts1`.`City`), CONCAT_WS('',   `Contacts1`.`City`), '') /* City */" => "City",
		"IF(    CHAR_LENGTH(`Contacts1`.`State`), CONCAT_WS('',   `Contacts1`.`State`), '') /* State */" => "State",
		"IF(    CHAR_LENGTH(`Contacts1`.`Zip`), CONCAT_WS('',   `Contacts1`.`Zip`), '') /* Zip */" => "Zip",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Bidders`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`Contacts1`.`MailingNameFull`), CONCAT_WS('',   `Contacts1`.`MailingNameFull`), '') /* Contact */" => "Contact",
		"`Bidders`.`BidNo`" => "Bid Number",
		"`Bidders`.`BidderType`" => "Bidder Type",
		"`Bidders`.`CheckedIn`" => "Checked In",
		"`Bidders`.`QuickPay`" => "Quick Pay",
		"`Bidders`.`TotalBids`" => "Total Bids",
		"`Bidders`.`TotalOwed`" => "Total Owed",
		"IF(    CHAR_LENGTH(`Contacts1`.`MailingNameFull`), CONCAT_WS('',   `Contacts1`.`MailingNameFull`), '') /* MailingName */" => "MailingName",
		"`Bidders`.`TablePreference`" => "Table Preference",
		"`Bidders`.`Card`" => "Card",
		"`Bidders`.`TotalPaid`" => "TotalPaid",
		"IF(    CHAR_LENGTH(`Contacts1`.`Business`), CONCAT_WS('',   `Contacts1`.`Business`), '') /* Business Name */" => "Business Name",
		"IF(    CHAR_LENGTH(`Contacts1`.`Address1`), CONCAT_WS('',   `Contacts1`.`Address1`), '') /* Address1 */" => "Address1",
		"IF(    CHAR_LENGTH(`Contacts1`.`Address2`), CONCAT_WS('',   `Contacts1`.`Address2`), '') /* Address2 */" => "Address2",
		"IF(    CHAR_LENGTH(`Contacts1`.`City`), CONCAT_WS('',   `Contacts1`.`City`), '') /* City */" => "City",
		"IF(    CHAR_LENGTH(`Contacts1`.`State`), CONCAT_WS('',   `Contacts1`.`State`), '') /* State */" => "State",
		"IF(    CHAR_LENGTH(`Contacts1`.`Zip`), CONCAT_WS('',   `Contacts1`.`Zip`), '') /* Zip */" => "Zip",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Bidders`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`Contacts1`.`MailingNameFull`), CONCAT_WS('',   `Contacts1`.`MailingNameFull`), '') /* Contact */" => "ContactID",
		"`Bidders`.`BidNo`" => "BidNo",
		"`Bidders`.`BidderType`" => "BidderType",
		"`Bidders`.`CheckedIn`" => "CheckedIn",
		"`Bidders`.`QuickPay`" => "QuickPay",
		"`Bidders`.`TotalBids`" => "TotalBids",
		"`Bidders`.`TotalOwed`" => "TotalOwed",
		"IF(    CHAR_LENGTH(`Contacts1`.`MailingNameFull`), CONCAT_WS('',   `Contacts1`.`MailingNameFull`), '') /* MailingName */" => "MailingName",
		"`Bidders`.`TablePreference`" => "TablePreference",
		"`Bidders`.`Card`" => "Card",
		"`Bidders`.`TotalPaid`" => "TotalPaid",
		"IF(    CHAR_LENGTH(`Contacts1`.`Business`), CONCAT_WS('',   `Contacts1`.`Business`), '') /* Business Name */" => "Business",
		"IF(    CHAR_LENGTH(`Contacts1`.`Address1`), CONCAT_WS('',   `Contacts1`.`Address1`), '') /* Address1 */" => "Address1",
		"IF(    CHAR_LENGTH(`Contacts1`.`Address2`), CONCAT_WS('',   `Contacts1`.`Address2`), '') /* Address2 */" => "Address2",
		"IF(    CHAR_LENGTH(`Contacts1`.`City`), CONCAT_WS('',   `Contacts1`.`City`), '') /* City */" => "City",
		"IF(    CHAR_LENGTH(`Contacts1`.`State`), CONCAT_WS('',   `Contacts1`.`State`), '') /* State */" => "State",
		"IF(    CHAR_LENGTH(`Contacts1`.`Zip`), CONCAT_WS('',   `Contacts1`.`Zip`), '') /* Zip */" => "Zip",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['ContactID' => 'Contact', ];

	$x->QueryFrom = "`Bidders` LEFT JOIN `Contacts` as Contacts1 ON `Contacts1`.`ID`=`Bidders`.`ContactID` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Bidders_view.php';
	$x->TableTitle = 'Bidders';
	$x->TableIcon = 'resources/table_icons/32Px - 010.png';
	$x->PrimaryKey = '`Bidders`.`ID`';
	$x->DefaultSortField = '3';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 100, 100, 100, ];
	$x->ColCaption = ['Contact', 'Bid Number', 'Bidder Type', 'Checked In', 'Quick Pay', 'Total Owed', 'Table Preference', 'Card', 'TotalPaid', 'Transactions', 'Payments', 'Tickets', ];
	$x->ColFieldName = ['ContactID', 'BidNo', 'BidderType', 'CheckedIn', 'QuickPay', 'TotalOwed', 'TablePreference', 'Card', 'TotalPaid', '%Transactions.BidderID%', '%Payments.BidderID%', '%Tickets.BidderID%', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 8, 10, 11, 12, -1, -1, -1, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Bidders_templateTV.html';
	$x->SelectedTemplate = 'templates/Bidders_templateTVS.html';
	$x->TemplateDV = 'templates/Bidders_templateDV.html';
	$x->TemplateDVP = 'templates/Bidders_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Bidders_init
	$render = true;
	if(function_exists('Bidders_init')) {
		$args = [];
		$render = Bidders_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Bidders_header
	$headerCode = '';
	if(function_exists('Bidders_header')) {
		$args = [];
		$headerCode = Bidders_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Bidders_footer
	$footerCode = '';
	if(function_exists('Bidders_footer')) {
		$args = [];
		$footerCode = Bidders_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
