<?php

// Data functions (insert, update, delete, form) for table Bidders

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function Bidders_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Bidders');
	if(!$arrPerm['insert']) return false;

	$data = [
		'ContactID' => Request::lookup('ContactID', ''),
		'BidNo' => Request::val('BidNo', ''),
		'BidderType' => Request::val('BidderType', 'Bidder'),
		'CheckedIn' => Request::val('CheckedIn', ''),
		'QuickPay' => Request::val('QuickPay', ''),
		'TablePreference' => Request::val('TablePreference', ''),
		'Card' => Request::val('Card', ''),
	];


	// automatic MailingName if passed as filterer
	if(Request::val('filterer_MailingName')) {
		$data['MailingName'] = Request::val('filterer_MailingName');
	}

	// automatic Business if passed as filterer
	if(Request::val('filterer_Business')) {
		$data['Business'] = Request::val('filterer_Business');
	}

	// automatic Address1 if passed as filterer
	if(Request::val('filterer_Address1')) {
		$data['Address1'] = Request::val('filterer_Address1');
	}

	// automatic Address2 if passed as filterer
	if(Request::val('filterer_Address2')) {
		$data['Address2'] = Request::val('filterer_Address2');
	}

	// automatic City if passed as filterer
	if(Request::val('filterer_City')) {
		$data['City'] = Request::val('filterer_City');
	}

	// automatic State if passed as filterer
	if(Request::val('filterer_State')) {
		$data['State'] = Request::val('filterer_State');
	}

	// automatic Zip if passed as filterer
	if(Request::val('filterer_Zip')) {
		$data['Zip'] = Request::val('filterer_Zip');
	}

	// hook: Bidders_before_insert
	if(function_exists('Bidders_before_insert')) {
		$args = [];
		if(!Bidders_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Bidders', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Bidders', $recID, calculated_fields()['Bidders']);

	// hook: Bidders_after_insert
	if(function_exists('Bidders_after_insert')) {
		$res = sql("SELECT * FROM `Bidders` WHERE `ID`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Bidders_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	// record owner is current user
	$recordOwner = getLoggedMemberID();
	set_record_owner('Bidders', $recID, $recordOwner);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Bidders_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Bidders_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Bidders_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Bidders', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Bidders_before_delete
	if(function_exists('Bidders_before_delete')) {
		$args = [];
		if(!Bidders_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: Transactions
	$res = sql("SELECT `ID` FROM `Bidders` WHERE `ID`='{$selected_id}'", $eo);
	$ID = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Transactions` WHERE `BidderID`='" . makeSafe($ID[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Transactions', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Transactions', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Bidders_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Bidders_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: Payments
	$res = sql("SELECT `ID` FROM `Bidders` WHERE `ID`='{$selected_id}'", $eo);
	$ID = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Payments` WHERE `BidderID`='" . makeSafe($ID[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Payments', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Payments', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Bidders_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Bidders_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: Tickets
	$res = sql("SELECT `ID` FROM `Bidders` WHERE `ID`='{$selected_id}'", $eo);
	$ID = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Tickets` WHERE `BidderID`='" . makeSafe($ID[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Tickets', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Tickets', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Bidders_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Bidders_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `Bidders` WHERE `ID`='{$selected_id}'", $eo);

	// hook: Bidders_after_delete
	if(function_exists('Bidders_after_delete')) {
		$args = [];
		Bidders_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Bidders' AND `pkValue`='{$selected_id}'", $eo);
}

function Bidders_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Bidders', $selected_id, 'edit')) return false;

	$data = [
		'ContactID' => Request::lookup('ContactID', ''),
		'BidNo' => Request::val('BidNo', ''),
		'BidderType' => Request::val('BidderType', ''),
		'CheckedIn' => Request::val('CheckedIn', ''),
		'QuickPay' => Request::val('QuickPay', ''),
		'TablePreference' => Request::val('TablePreference', ''),
		'Card' => Request::val('Card', ''),
	];

	// get existing values
	$old_data = getRecord('Bidders', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Bidders_before_update
	if(function_exists('Bidders_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Bidders_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Bidders', 
		backtick_keys_once($set), 
		['`ID`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Bidders_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Bidders', $data['selectedID'], calculated_fields()['Bidders']);

	// hook: Bidders_after_update
	if(function_exists('Bidders_after_update')) {
		$res = sql("SELECT * FROM `Bidders` WHERE `ID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['ID'];
		$args = ['old_data' => $old_data];
		if(!Bidders_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('Bidders', $selected_id);
}

function Bidders_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Bidders');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_ContactID = Request::val('filterer_ContactID');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: ContactID
	$combo_ContactID = new DataCombo;
	// combobox: BidderType
	$combo_BidderType = new Combo;
	$combo_BidderType->ListType = 2;
	$combo_BidderType->MultipleSeparator = ', ';
	$combo_BidderType->ListBoxHeight = 10;
	$combo_BidderType->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/Bidders.BidderType.csv')) {
		$BidderType_data = addslashes(implode('', @file(__DIR__ . '/hooks/Bidders.BidderType.csv')));
		$combo_BidderType->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($BidderType_data))));
		$combo_BidderType->ListData = $combo_BidderType->ListItem;
	} else {
		$combo_BidderType->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Bidder;;Donor"))));
		$combo_BidderType->ListData = $combo_BidderType->ListItem;
	}
	$combo_BidderType->SelectName = 'BidderType';
	// combobox: CheckedIn
	$combo_CheckedIn = new Combo;
	$combo_CheckedIn->ListType = 2;
	$combo_CheckedIn->MultipleSeparator = ', ';
	$combo_CheckedIn->ListBoxHeight = 10;
	$combo_CheckedIn->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/Bidders.CheckedIn.csv')) {
		$CheckedIn_data = addslashes(implode('', @file(__DIR__ . '/hooks/Bidders.CheckedIn.csv')));
		$combo_CheckedIn->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($CheckedIn_data))));
		$combo_CheckedIn->ListData = $combo_CheckedIn->ListItem;
	} else {
		$combo_CheckedIn->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Yes"))));
		$combo_CheckedIn->ListData = $combo_CheckedIn->ListItem;
	}
	$combo_CheckedIn->SelectName = 'CheckedIn';
	// combobox: QuickPay
	$combo_QuickPay = new Combo;
	$combo_QuickPay->ListType = 2;
	$combo_QuickPay->MultipleSeparator = ', ';
	$combo_QuickPay->ListBoxHeight = 10;
	$combo_QuickPay->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/Bidders.QuickPay.csv')) {
		$QuickPay_data = addslashes(implode('', @file(__DIR__ . '/hooks/Bidders.QuickPay.csv')));
		$combo_QuickPay->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($QuickPay_data))));
		$combo_QuickPay->ListData = $combo_QuickPay->ListItem;
	} else {
		$combo_QuickPay->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Yes;;No"))));
		$combo_QuickPay->ListData = $combo_QuickPay->ListItem;
	}
	$combo_QuickPay->SelectName = 'QuickPay';

	if($selected_id) {
		if(!check_record_permission('Bidders', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('Bidders', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('Bidders', $selected_id, 'delete');

		$res = sql("SELECT * FROM `Bidders` WHERE `ID`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Bidders_view.php', false);
		}
		$combo_ContactID->SelectedData = $row['ContactID'];
		$combo_BidderType->SelectedData = $row['BidderType'];
		$combo_CheckedIn->SelectedData = $row['CheckedIn'];
		$combo_QuickPay->SelectedData = $row['QuickPay'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_ContactID->SelectedData = $filterer_ContactID;
		$combo_BidderType->SelectedText = (isset($filterField[1]) && $filterField[1] == '4' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8('Bidder'));
		$combo_CheckedIn->SelectedText = (isset($filterField[1]) && $filterField[1] == '5' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
		$combo_QuickPay->SelectedText = (isset($filterField[1]) && $filterField[1] == '6' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
	}
	$combo_ContactID->HTML = '<span id="ContactID-container' . $rnd1 . '"></span><input type="hidden" name="ContactID" id="ContactID' . $rnd1 . '" value="' . html_attr($combo_ContactID->SelectedData) . '">';
	$combo_ContactID->MatchText = '<span id="ContactID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="ContactID" id="ContactID' . $rnd1 . '" value="' . html_attr($combo_ContactID->SelectedData) . '">';
	$combo_BidderType->Render();
	$combo_CheckedIn->Render();
	$combo_QuickPay->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_ContactID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['ContactID'] : htmlspecialchars($filterer_ContactID, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(ContactID_reload__RAND__) == 'function') ContactID_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function ContactID_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#ContactID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_ContactID__RAND__.value, t: 'Bidders', f: 'ContactID' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="ContactID"]').val(resp.results[0].id);
							$j('[id=ContactID-container-readonly__RAND__]').html('<span class="match-text" id="ContactID-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Contacts_view_parent]').hide(); } else { $j('.btn[id=Contacts_view_parent]').show(); }


							if(typeof(ContactID_update_autofills__RAND__) == 'function') ContactID_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Bidders', f: 'ContactID' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_ContactID__RAND__.value = e.added.id;
				AppGini.current_ContactID__RAND__.text = e.added.text;
				$j('[name="ContactID"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Contacts_view_parent]').hide(); } else { $j('.btn[id=Contacts_view_parent]').show(); }


				if(typeof(ContactID_update_autofills__RAND__) == 'function') ContactID_update_autofills__RAND__();
			});

			if(!$j("#ContactID-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_ContactID__RAND__.value, t: 'Bidders', f: 'ContactID' },
					success: function(resp) {
						$j('[name="ContactID"]').val(resp.results[0].id);
						$j('[id=ContactID-container-readonly__RAND__]').html('<span class="match-text" id="ContactID-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Contacts_view_parent]').hide(); } else { $j('.btn[id=Contacts_view_parent]').show(); }

						if(typeof(ContactID_update_autofills__RAND__) == 'function') ContactID_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_ContactID__RAND__.value, t: 'Bidders', f: 'ContactID' },
				success: function(resp) {
					$j('[id=ContactID-container__RAND__], [id=ContactID-container-readonly__RAND__]').html('<span class="match-text" id="ContactID-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Contacts_view_parent]').hide(); } else { $j('.btn[id=Contacts_view_parent]').show(); }

					if(typeof(ContactID_update_autofills__RAND__) == 'function') ContactID_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Bidders_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Bidders_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Bidder details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Bidders_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Bidders_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Bidders_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#ContactID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#ContactID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#BidNo').replaceWith('<div class=\"form-control-static\" id=\"BidNo\">' + (jQuery('#BidNo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('input[name=BidderType]').parent().html('<div class=\"form-control-static\">' + jQuery('input[name=BidderType]:checked').next().text() + '</div>')\n";
		$jsReadOnly .= "\tjQuery('input[name=CheckedIn]').parent().html('<div class=\"form-control-static\">' + jQuery('input[name=CheckedIn]:checked').next().text() + '</div>')\n";
		$jsReadOnly .= "\tjQuery('input[name=QuickPay]').parent().html('<div class=\"form-control-static\">' + jQuery('input[name=QuickPay]:checked').next().text() + '</div>')\n";
		$jsReadOnly .= "\tjQuery('#TablePreference').replaceWith('<div class=\"form-control-static\" id=\"TablePreference\">' + (jQuery('#TablePreference').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Card').replaceWith('<div class=\"form-control-static\" id=\"Card\">' + (jQuery('#Card').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(ContactID)%%>', $combo_ContactID->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(ContactID)%%>', $combo_ContactID->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(ContactID)%%>', urlencode($combo_ContactID->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(BidderType)%%>', $combo_BidderType->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(BidderType)%%>', $combo_BidderType->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(CheckedIn)%%>', $combo_CheckedIn->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(CheckedIn)%%>', $combo_CheckedIn->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(QuickPay)%%>', $combo_QuickPay->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(QuickPay)%%>', $combo_QuickPay->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['ContactID' => ['Contacts', 'Contact'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(ID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ContactID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(BidNo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(BidderType)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(CheckedIn)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(QuickPay)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(TotalBids)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(TotalOwed)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(TablePreference)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Card)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(TotalPaid)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ID)%%>', safe_html($urow['ID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ID)%%>', html_attr($row['ID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ID)%%>', urlencode($urow['ID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ContactID)%%>', safe_html($urow['ContactID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ContactID)%%>', html_attr($row['ContactID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ContactID)%%>', urlencode($urow['ContactID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(BidNo)%%>', safe_html($urow['BidNo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(BidNo)%%>', html_attr($row['BidNo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(BidNo)%%>', urlencode($urow['BidNo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(BidderType)%%>', safe_html($urow['BidderType']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(BidderType)%%>', html_attr($row['BidderType']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(BidderType)%%>', urlencode($urow['BidderType']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(CheckedIn)%%>', safe_html($urow['CheckedIn']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(CheckedIn)%%>', html_attr($row['CheckedIn']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CheckedIn)%%>', urlencode($urow['CheckedIn']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(QuickPay)%%>', safe_html($urow['QuickPay']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(QuickPay)%%>', html_attr($row['QuickPay']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(QuickPay)%%>', urlencode($urow['QuickPay']), $templateCode);
		$templateCode = str_replace('<%%VALUE(TotalBids)%%>', safe_html($urow['TotalBids']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(TotalBids)%%>', urlencode($urow['TotalBids']), $templateCode);
		$templateCode = str_replace('<%%VALUE(TotalOwed)%%>', safe_html($urow['TotalOwed']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(TotalOwed)%%>', urlencode($urow['TotalOwed']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(TablePreference)%%>', safe_html($urow['TablePreference']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(TablePreference)%%>', html_attr($row['TablePreference']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(TablePreference)%%>', urlencode($urow['TablePreference']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Card)%%>', safe_html($urow['Card']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Card)%%>', html_attr($row['Card']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Card)%%>', urlencode($urow['Card']), $templateCode);
		$templateCode = str_replace('<%%VALUE(TotalPaid)%%>', safe_html($urow['TotalPaid']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(TotalPaid)%%>', urlencode($urow['TotalPaid']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(ID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ContactID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ContactID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(BidNo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(BidNo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(BidderType)%%>', 'Bidder', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(BidderType)%%>', urlencode('Bidder'), $templateCode);
		$templateCode = str_replace('<%%VALUE(CheckedIn)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CheckedIn)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(QuickPay)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(QuickPay)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(TotalBids)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(TotalBids)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(TotalOwed)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(TotalOwed)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(TablePreference)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(TablePreference)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Card)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Card)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(TotalPaid)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(TotalPaid)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tContactID_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'Bidders_autofill.php?rnd1=$rnd1&mfk=ContactID&id=' + encodeURIComponent('".addslashes($row['ContactID'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'Bidders_autofill.php?rnd1=$rnd1&mfk=ContactID&id=' + encodeURIComponent(AppGini.current_ContactID{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#ContactID$rnd1').prop('disabled', true); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm['insert'] || (($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3)) ? "\$j('#ContactID$rnd1').prop('disabled', false); " : "\$j('#ContactID$rnd1').prop('disabled', true); ")." \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#ContactID_caption').length) \$j('#ContactID_caption').click(function() { ContactID_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Bidders');
	if($selected_id) {
		$jdata = get_joined_record('Bidders', $selected_id);
		if($jdata === false) $jdata = get_defaults('Bidders');
		$rdata = $row;
	}
	$templateCode .= loadView('Bidders-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Bidders_dv
	if(function_exists('Bidders_dv')) {
		$args = [];
		Bidders_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}