<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Contacts.php');
	include_once(__DIR__ . '/Contacts_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Contacts');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Contacts';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Contacts`.`ID`" => "ID",
		"`Contacts`.`FirstName`" => "FirstName",
		"`Contacts`.`LastName`" => "LastName",
		"`Contacts`.`SpouseName`" => "SpouseName",
		"`Contacts`.`Business`" => "Business",
		"`Contacts`.`Address1`" => "Address1",
		"`Contacts`.`Address2`" => "Address2",
		"`Contacts`.`City`" => "City",
		"`Contacts`.`State`" => "State",
		"`Contacts`.`Zip`" => "Zip",
		"CONCAT_WS('-', LEFT(`Contacts`.`Cell`,3), MID(`Contacts`.`Cell`,4,3), RIGHT(`Contacts`.`Cell`,4))" => "Cell",
		"CONCAT_WS('-', LEFT(`Contacts`.`Phone`,3), MID(`Contacts`.`Phone`,4,3), RIGHT(`Contacts`.`Phone`,4))" => "Phone",
		"`Contacts`.`Email`" => "Email",
		"`Contacts`.`Status`" => "Status",
		"`Contacts`.`ContactMethod`" => "ContactMethod",
		"`Contacts`.`MailingName`" => "MailingName",
		"`Contacts`.`MailingNameFull`" => "MailingNameFull",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Contacts`.`ID`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Contacts`.`ID`" => "ID",
		"`Contacts`.`FirstName`" => "FirstName",
		"`Contacts`.`LastName`" => "LastName",
		"`Contacts`.`SpouseName`" => "SpouseName",
		"`Contacts`.`Business`" => "Business",
		"`Contacts`.`Address1`" => "Address1",
		"`Contacts`.`Address2`" => "Address2",
		"`Contacts`.`City`" => "City",
		"`Contacts`.`State`" => "State",
		"`Contacts`.`Zip`" => "Zip",
		"CONCAT_WS('-', LEFT(`Contacts`.`Cell`,3), MID(`Contacts`.`Cell`,4,3), RIGHT(`Contacts`.`Cell`,4))" => "Cell",
		"CONCAT_WS('-', LEFT(`Contacts`.`Phone`,3), MID(`Contacts`.`Phone`,4,3), RIGHT(`Contacts`.`Phone`,4))" => "Phone",
		"`Contacts`.`Email`" => "Email",
		"`Contacts`.`Status`" => "Status",
		"`Contacts`.`ContactMethod`" => "ContactMethod",
		"`Contacts`.`MailingName`" => "MailingName",
		"`Contacts`.`MailingNameFull`" => "MailingNameFull",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Contacts`.`ID`" => "ID",
		"`Contacts`.`FirstName`" => "First Name",
		"`Contacts`.`LastName`" => "Last Name",
		"`Contacts`.`SpouseName`" => "Spouse Name",
		"`Contacts`.`Business`" => "Business Name",
		"`Contacts`.`Address1`" => "Address1",
		"`Contacts`.`Address2`" => "Address2",
		"`Contacts`.`City`" => "City",
		"`Contacts`.`State`" => "State",
		"`Contacts`.`Zip`" => "Zip",
		"`Contacts`.`Cell`" => "Cell",
		"`Contacts`.`Phone`" => "Phone",
		"`Contacts`.`Email`" => "Email",
		"`Contacts`.`Status`" => "Status",
		"`Contacts`.`ContactMethod`" => "Contact Method",
		"`Contacts`.`MailingName`" => "Mailing Name",
		"`Contacts`.`MailingNameFull`" => "Mailing Name Full",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Contacts`.`ID`" => "ID",
		"`Contacts`.`FirstName`" => "FirstName",
		"`Contacts`.`LastName`" => "LastName",
		"`Contacts`.`SpouseName`" => "SpouseName",
		"`Contacts`.`Business`" => "Business",
		"`Contacts`.`Address1`" => "Address1",
		"`Contacts`.`Address2`" => "Address2",
		"`Contacts`.`City`" => "City",
		"`Contacts`.`State`" => "State",
		"`Contacts`.`Zip`" => "Zip",
		"CONCAT_WS('-', LEFT(`Contacts`.`Cell`,3), MID(`Contacts`.`Cell`,4,3), RIGHT(`Contacts`.`Cell`,4))" => "Cell",
		"CONCAT_WS('-', LEFT(`Contacts`.`Phone`,3), MID(`Contacts`.`Phone`,4,3), RIGHT(`Contacts`.`Phone`,4))" => "Phone",
		"`Contacts`.`Email`" => "Email",
		"`Contacts`.`Status`" => "Status",
		"`Contacts`.`ContactMethod`" => "ContactMethod",
		"`Contacts`.`MailingName`" => "MailingName",
		"`Contacts`.`MailingNameFull`" => "MailingNameFull",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`Contacts` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = (getLoggedAdmin() !== false);
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Contacts_view.php';
	$x->RedirectAfterInsert = 'Contacts_view.php';
	$x->TableTitle = 'Supporters';
	$x->TableIcon = 'resources/table_icons/32Px - 002.png';
	$x->PrimaryKey = '`Contacts`.`ID`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, 150, 150, 150, 150, 100, 100, 150, 150, 150, 150, 150, 150, 100, 100, ];
	$x->ColCaption = ['ID', 'First Name', 'Last Name', 'Spouse Name', 'Business Name', 'Address1', 'Address2', 'City', 'State', 'Zip', 'Cell', 'Phone', 'Email', 'Donations', 'Bidders', ];
	$x->ColFieldName = ['ID', 'FirstName', 'LastName', 'SpouseName', 'Business', 'Address1', 'Address2', 'City', 'State', 'Zip', 'Cell', 'Phone', 'Email', '%Donations.ContactID%', '%Bidders.ContactID%', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, -1, -1, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Contacts_templateTV.html';
	$x->SelectedTemplate = 'templates/Contacts_templateTVS.html';
	$x->TemplateDV = 'templates/Contacts_templateDV.html';
	$x->TemplateDVP = 'templates/Contacts_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Contacts_init
	$render = true;
	if(function_exists('Contacts_init')) {
		$args = [];
		$render = Contacts_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Contacts_header
	$headerCode = '';
	if(function_exists('Contacts_header')) {
		$args = [];
		$headerCode = Contacts_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Contacts_footer
	$footerCode = '';
	if(function_exists('Contacts_footer')) {
		$args = [];
		$footerCode = Contacts_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
