<?php

// Data functions (insert, update, delete, form) for table Donations

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function Donations_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Donations');
	if(!$arrPerm['insert']) return false;

	$data = [
		'DonationName' => Request::val('DonationName', ''),
		'Description' => Request::val('Description', ''),
		'Restrictions' => Request::val('Restrictions', ''),
		'Value' => Request::val('Value', ''),
		'CatalogID' => Request::lookup('CatalogID', ''),
		'ContactID' => Request::lookup('ContactID', ''),
		'ContactPerson' => Request::val('ContactPerson', ''),
		'ContactPhone' => Request::val('ContactPhone', ''),
		'ItemStatus' => Request::multipleChoice('ItemStatus', ''),
		'ProcuredBy' => Request::val('ProcuredBy', ''),
		'DateProcured' => Request::dateComponents('DateProcured', ''),
		'AdditionalInfo' => Request::multipleChoice('AdditionalInfo', ''),
		'Thanks' => Request::val('Thanks', ''),
		'Notes' => Request::val('Notes', ''),
	];


	// hook: Donations_before_insert
	if(function_exists('Donations_before_insert')) {
		$args = [];
		if(!Donations_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Donations', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Donations', $recID, calculated_fields()['Donations']);

	// hook: Donations_after_insert
	if(function_exists('Donations_after_insert')) {
		$res = sql("SELECT * FROM `Donations` WHERE `ID`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Donations_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	// record owner is current user
	$recordOwner = getLoggedMemberID();
	set_record_owner('Donations', $recID, $recordOwner);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Donations_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Donations_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Donations_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Donations', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Donations_before_delete
	if(function_exists('Donations_before_delete')) {
		$args = [];
		if(!Donations_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `Donations` WHERE `ID`='{$selected_id}'", $eo);

	// hook: Donations_after_delete
	if(function_exists('Donations_after_delete')) {
		$args = [];
		Donations_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Donations' AND `pkValue`='{$selected_id}'", $eo);
}

function Donations_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Donations', $selected_id, 'edit')) return false;

	$data = [
		'DonationName' => Request::val('DonationName', ''),
		'Description' => Request::val('Description', ''),
		'Restrictions' => Request::val('Restrictions', ''),
		'Value' => Request::val('Value', ''),
		'CatalogID' => Request::lookup('CatalogID', ''),
		'ContactID' => Request::lookup('ContactID', ''),
		'ContactPerson' => Request::val('ContactPerson', ''),
		'ContactPhone' => Request::val('ContactPhone', ''),
		'ItemStatus' => Request::multipleChoice('ItemStatus', ''),
		'ProcuredBy' => Request::val('ProcuredBy', ''),
		'DateProcured' => Request::dateComponents('DateProcured', ''),
		'AdditionalInfo' => Request::multipleChoice('AdditionalInfo', ''),
		'Thanks' => Request::val('Thanks', ''),
		'Notes' => Request::val('Notes', ''),
	];

	// get existing values
	$old_data = getRecord('Donations', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Donations_before_update
	if(function_exists('Donations_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Donations_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Donations', 
		backtick_keys_once($set), 
		['`ID`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Donations_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Donations', $data['selectedID'], calculated_fields()['Donations']);

	// hook: Donations_after_update
	if(function_exists('Donations_after_update')) {
		$res = sql("SELECT * FROM `Donations` WHERE `ID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['ID'];
		$args = ['old_data' => $old_data];
		if(!Donations_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('Donations', $selected_id);
}

function Donations_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Donations');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_CatalogID = Request::val('filterer_CatalogID');
	$filterer_ContactID = Request::val('filterer_ContactID');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: CatalogID
	$combo_CatalogID = new DataCombo;
	// combobox: ContactID
	$combo_ContactID = new DataCombo;
	// combobox: ItemStatus
	$combo_ItemStatus = new Combo;
	$combo_ItemStatus->ListType = 3;
	$combo_ItemStatus->MultipleSeparator = ', ';
	$combo_ItemStatus->ListBoxHeight = 10;
	$combo_ItemStatus->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/Donations.ItemStatus.csv')) {
		$ItemStatus_data = addslashes(implode('', @file(__DIR__ . '/hooks/Donations.ItemStatus.csv')));
		$combo_ItemStatus->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($ItemStatus_data))));
		$combo_ItemStatus->ListData = $combo_ItemStatus->ListItem;
	} else {
		$combo_ItemStatus->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Needs Gift Certificate;;Item Received;;Other (see notes)"))));
		$combo_ItemStatus->ListData = $combo_ItemStatus->ListItem;
	}
	$combo_ItemStatus->SelectName = 'ItemStatus';
	// combobox: DateProcured
	$combo_DateProcured = new DateCombo;
	$combo_DateProcured->DateFormat = "mdy";
	$combo_DateProcured->MinYear = defined('Donations.DateProcured.MinYear') ? constant('Donations.DateProcured.MinYear') : 1900;
	$combo_DateProcured->MaxYear = defined('Donations.DateProcured.MaxYear') ? constant('Donations.DateProcured.MaxYear') : 2100;
	$combo_DateProcured->DefaultDate = parseMySQLDate('', '');
	$combo_DateProcured->MonthNames = $Translation['month names'];
	$combo_DateProcured->NamePrefix = 'DateProcured';
	// combobox: AdditionalInfo
	$combo_AdditionalInfo = new Combo;
	$combo_AdditionalInfo->ListType = 3;
	$combo_AdditionalInfo->MultipleSeparator = ', ';
	$combo_AdditionalInfo->ListBoxHeight = 10;
	$combo_AdditionalInfo->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/Donations.AdditionalInfo.csv')) {
		$AdditionalInfo_data = addslashes(implode('', @file(__DIR__ . '/hooks/Donations.AdditionalInfo.csv')));
		$combo_AdditionalInfo->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($AdditionalInfo_data))));
		$combo_AdditionalInfo->ListData = $combo_AdditionalInfo->ListItem;
	} else {
		$combo_AdditionalInfo->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Is a Gift Certificate;;Anonymous Donor"))));
		$combo_AdditionalInfo->ListData = $combo_AdditionalInfo->ListItem;
	}
	$combo_AdditionalInfo->SelectName = 'AdditionalInfo';
	// combobox: Thanks
	$combo_Thanks = new Combo;
	$combo_Thanks->ListType = 0;
	$combo_Thanks->MultipleSeparator = ', ';
	$combo_Thanks->ListBoxHeight = 10;
	$combo_Thanks->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/Donations.Thanks.csv')) {
		$Thanks_data = addslashes(implode('', @file(__DIR__ . '/hooks/Donations.Thanks.csv')));
		$combo_Thanks->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($Thanks_data))));
		$combo_Thanks->ListData = $combo_Thanks->ListItem;
	} else {
		$combo_Thanks->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Yes;;No"))));
		$combo_Thanks->ListData = $combo_Thanks->ListItem;
	}
	$combo_Thanks->SelectName = 'Thanks';

	if($selected_id) {
		if(!check_record_permission('Donations', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('Donations', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('Donations', $selected_id, 'delete');

		$res = sql("SELECT * FROM `Donations` WHERE `ID`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Donations_view.php', false);
		}
		$combo_CatalogID->SelectedData = $row['CatalogID'];
		$combo_ContactID->SelectedData = $row['ContactID'];
		$combo_ItemStatus->SelectedData = $row['ItemStatus'];
		$combo_DateProcured->DefaultDate = $row['DateProcured'];
		$combo_AdditionalInfo->SelectedData = $row['AdditionalInfo'];
		$combo_Thanks->SelectedData = $row['Thanks'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_CatalogID->SelectedData = $filterer_CatalogID;
		$combo_ContactID->SelectedData = $filterer_ContactID;
		$combo_Thanks->SelectedText = (isset($filterField[1]) && $filterField[1] == '14' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
	}
	$combo_CatalogID->HTML = '<span id="CatalogID-container' . $rnd1 . '"></span><input type="hidden" name="CatalogID" id="CatalogID' . $rnd1 . '" value="' . html_attr($combo_CatalogID->SelectedData) . '">';
	$combo_CatalogID->MatchText = '<span id="CatalogID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="CatalogID" id="CatalogID' . $rnd1 . '" value="' . html_attr($combo_CatalogID->SelectedData) . '">';
	$combo_ContactID->HTML = '<span id="ContactID-container' . $rnd1 . '"></span><input type="hidden" name="ContactID" id="ContactID' . $rnd1 . '" value="' . html_attr($combo_ContactID->SelectedData) . '">';
	$combo_ContactID->MatchText = '<span id="ContactID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="ContactID" id="ContactID' . $rnd1 . '" value="' . html_attr($combo_ContactID->SelectedData) . '">';
	$combo_ItemStatus->Render();
	$combo_AdditionalInfo->Render();
	$combo_Thanks->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_CatalogID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['CatalogID'] : htmlspecialchars($filterer_CatalogID, ENT_QUOTES)); ?>"};
		AppGini.current_ContactID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['ContactID'] : htmlspecialchars($filterer_ContactID, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(CatalogID_reload__RAND__) == 'function') CatalogID_reload__RAND__();
				if(typeof(ContactID_reload__RAND__) == 'function') ContactID_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function CatalogID_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#CatalogID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_CatalogID__RAND__.value, t: 'Donations', f: 'CatalogID' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="CatalogID"]').val(resp.results[0].id);
							$j('[id=CatalogID-container-readonly__RAND__]').html('<span class="match-text" id="CatalogID-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Catalog_view_parent]').hide(); } else { $j('.btn[id=Catalog_view_parent]').show(); }


							if(typeof(CatalogID_update_autofills__RAND__) == 'function') CatalogID_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Donations', f: 'CatalogID' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_CatalogID__RAND__.value = e.added.id;
				AppGini.current_CatalogID__RAND__.text = e.added.text;
				$j('[name="CatalogID"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Catalog_view_parent]').hide(); } else { $j('.btn[id=Catalog_view_parent]').show(); }


				if(typeof(CatalogID_update_autofills__RAND__) == 'function') CatalogID_update_autofills__RAND__();
			});

			if(!$j("#CatalogID-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_CatalogID__RAND__.value, t: 'Donations', f: 'CatalogID' },
					success: function(resp) {
						$j('[name="CatalogID"]').val(resp.results[0].id);
						$j('[id=CatalogID-container-readonly__RAND__]').html('<span class="match-text" id="CatalogID-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Catalog_view_parent]').hide(); } else { $j('.btn[id=Catalog_view_parent]').show(); }

						if(typeof(CatalogID_update_autofills__RAND__) == 'function') CatalogID_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_CatalogID__RAND__.value, t: 'Donations', f: 'CatalogID' },
				success: function(resp) {
					$j('[id=CatalogID-container__RAND__], [id=CatalogID-container-readonly__RAND__]').html('<span class="match-text" id="CatalogID-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Catalog_view_parent]').hide(); } else { $j('.btn[id=Catalog_view_parent]').show(); }

					if(typeof(CatalogID_update_autofills__RAND__) == 'function') CatalogID_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function ContactID_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#ContactID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_ContactID__RAND__.value, t: 'Donations', f: 'ContactID' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="ContactID"]').val(resp.results[0].id);
							$j('[id=ContactID-container-readonly__RAND__]').html('<span class="match-text" id="ContactID-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Contacts_view_parent]').hide(); } else { $j('.btn[id=Contacts_view_parent]').show(); }


							if(typeof(ContactID_update_autofills__RAND__) == 'function') ContactID_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Donations', f: 'ContactID' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_ContactID__RAND__.value = e.added.id;
				AppGini.current_ContactID__RAND__.text = e.added.text;
				$j('[name="ContactID"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Contacts_view_parent]').hide(); } else { $j('.btn[id=Contacts_view_parent]').show(); }


				if(typeof(ContactID_update_autofills__RAND__) == 'function') ContactID_update_autofills__RAND__();
			});

			if(!$j("#ContactID-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_ContactID__RAND__.value, t: 'Donations', f: 'ContactID' },
					success: function(resp) {
						$j('[name="ContactID"]').val(resp.results[0].id);
						$j('[id=ContactID-container-readonly__RAND__]').html('<span class="match-text" id="ContactID-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Contacts_view_parent]').hide(); } else { $j('.btn[id=Contacts_view_parent]').show(); }

						if(typeof(ContactID_update_autofills__RAND__) == 'function') ContactID_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_ContactID__RAND__.value, t: 'Donations', f: 'ContactID' },
				success: function(resp) {
					$j('[id=ContactID-container__RAND__], [id=ContactID-container-readonly__RAND__]').html('<span class="match-text" id="ContactID-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Contacts_view_parent]').hide(); } else { $j('.btn[id=Contacts_view_parent]').show(); }

					if(typeof(ContactID_update_autofills__RAND__) == 'function') ContactID_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Donations_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Donations_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Donation details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Donations_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Donations_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Donations_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#DonationName').replaceWith('<div class=\"form-control-static\" id=\"DonationName\">' + (jQuery('#DonationName').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Value').replaceWith('<div class=\"form-control-static\" id=\"Value\">' + (jQuery('#Value').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#CatalogID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#CatalogID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#ContactID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#ContactID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#ContactPerson').replaceWith('<div class=\"form-control-static\" id=\"ContactPerson\">' + (jQuery('#ContactPerson').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#ContactPhone').replaceWith('<div class=\"form-control-static\" id=\"ContactPhone\">' + (jQuery('#ContactPhone').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#ItemStatus').replaceWith('<div class=\"form-control-static\" id=\"ItemStatus\">' + (jQuery('#ItemStatus').val() || '') + '</div>'); jQuery('#ItemStatus-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#s2id_ItemStatus').remove();\n";
		$jsReadOnly .= "\tjQuery('#ProcuredBy').replaceWith('<div class=\"form-control-static\" id=\"ProcuredBy\">' + (jQuery('#ProcuredBy').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#DateProcured').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#DateProcuredDay, #DateProcuredMonth, #DateProcuredYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#AdditionalInfo').replaceWith('<div class=\"form-control-static\" id=\"AdditionalInfo\">' + (jQuery('#AdditionalInfo').val() || '') + '</div>'); jQuery('#AdditionalInfo-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#s2id_AdditionalInfo').remove();\n";
		$jsReadOnly .= "\tjQuery('#Thanks').replaceWith('<div class=\"form-control-static\" id=\"Thanks\">' + (jQuery('#Thanks').val() || '') + '</div>'); jQuery('#Thanks-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(CatalogID)%%>', $combo_CatalogID->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(CatalogID)%%>', $combo_CatalogID->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(CatalogID)%%>', urlencode($combo_CatalogID->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(ContactID)%%>', $combo_ContactID->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(ContactID)%%>', $combo_ContactID->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(ContactID)%%>', urlencode($combo_ContactID->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(ItemStatus)%%>', $combo_ItemStatus->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(ItemStatus)%%>', $combo_ItemStatus->SelectedData, $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(DateProcured)%%>', 
		($selected_id && !$arrPerm['edit'] && ($noSaveAsCopy || !$arrPerm['insert']) ? 
			'<div class="form-control-static">' . $combo_DateProcured->GetHTML(true) . '</div>' : 
			$combo_DateProcured->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(DateProcured)%%>', $combo_DateProcured->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(AdditionalInfo)%%>', $combo_AdditionalInfo->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(AdditionalInfo)%%>', $combo_AdditionalInfo->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(Thanks)%%>', $combo_Thanks->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Thanks)%%>', $combo_Thanks->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['CatalogID' => ['Catalog', 'Catalog Number'], 'ContactID' => ['Contacts', 'Donor Name Lookup'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(ID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(DonationName)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Description)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Restrictions)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Value)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(CatalogID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ContactID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ContactPerson)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ContactPhone)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ItemStatus)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ProcuredBy)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(DateProcured)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(AdditionalInfo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Thanks)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Notes)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ID)%%>', safe_html($urow['ID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ID)%%>', html_attr($row['ID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ID)%%>', urlencode($urow['ID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(DonationName)%%>', safe_html($urow['DonationName']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(DonationName)%%>', html_attr($row['DonationName']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DonationName)%%>', urlencode($urow['DonationName']), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(Description)%%>', '<textarea name="Description" id="Description" rows="5">' . safe_html(htmlspecialchars_decode($row['Description'])) . '</textarea>', $templateCode);
		} else {
			$templateCode = str_replace('<%%HTMLAREA(Description)%%>', '<div id="Description" class="form-control-static">' . $row['Description'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(Description)%%>', nl2br($row['Description']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Description)%%>', urlencode($urow['Description']), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(Restrictions)%%>', '<textarea name="Restrictions" id="Restrictions" rows="5">' . safe_html(htmlspecialchars_decode($row['Restrictions'])) . '</textarea>', $templateCode);
		} else {
			$templateCode = str_replace('<%%HTMLAREA(Restrictions)%%>', '<div id="Restrictions" class="form-control-static">' . $row['Restrictions'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(Restrictions)%%>', nl2br($row['Restrictions']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Restrictions)%%>', urlencode($urow['Restrictions']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Value)%%>', safe_html($urow['Value']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Value)%%>', html_attr($row['Value']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Value)%%>', urlencode($urow['Value']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(CatalogID)%%>', safe_html($urow['CatalogID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(CatalogID)%%>', html_attr($row['CatalogID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CatalogID)%%>', urlencode($urow['CatalogID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ContactID)%%>', safe_html($urow['ContactID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ContactID)%%>', html_attr($row['ContactID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ContactID)%%>', urlencode($urow['ContactID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ContactPerson)%%>', safe_html($urow['ContactPerson']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ContactPerson)%%>', html_attr($row['ContactPerson']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ContactPerson)%%>', urlencode($urow['ContactPerson']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ContactPhone)%%>', safe_html($urow['ContactPhone']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ContactPhone)%%>', html_attr($row['ContactPhone']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ContactPhone)%%>', urlencode($urow['ContactPhone']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ItemStatus)%%>', safe_html($urow['ItemStatus']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ItemStatus)%%>', html_attr($row['ItemStatus']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ItemStatus)%%>', urlencode($urow['ItemStatus']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ProcuredBy)%%>', safe_html($urow['ProcuredBy']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ProcuredBy)%%>', html_attr($row['ProcuredBy']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ProcuredBy)%%>', urlencode($urow['ProcuredBy']), $templateCode);
		$templateCode = str_replace('<%%VALUE(DateProcured)%%>', app_datetime($row['DateProcured']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DateProcured)%%>', urlencode(app_datetime($urow['DateProcured'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(AdditionalInfo)%%>', safe_html($urow['AdditionalInfo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(AdditionalInfo)%%>', html_attr($row['AdditionalInfo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(AdditionalInfo)%%>', urlencode($urow['AdditionalInfo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Thanks)%%>', safe_html($urow['Thanks']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Thanks)%%>', html_attr($row['Thanks']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Thanks)%%>', urlencode($urow['Thanks']), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(Notes)%%>', '<textarea name="Notes" id="Notes" rows="5">' . safe_html(htmlspecialchars_decode($row['Notes'])) . '</textarea>', $templateCode);
		} else {
			$templateCode = str_replace('<%%HTMLAREA(Notes)%%>', '<div id="Notes" class="form-control-static">' . $row['Notes'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(Notes)%%>', nl2br($row['Notes']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Notes)%%>', urlencode($urow['Notes']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(ID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(DonationName)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DonationName)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(Description)%%>', '<textarea name="Description" id="Description" rows="5"></textarea>', $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(Restrictions)%%>', '<textarea name="Restrictions" id="Restrictions" rows="5"></textarea>', $templateCode);
		$templateCode = str_replace('<%%VALUE(Value)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Value)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(CatalogID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CatalogID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ContactID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ContactID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ContactPerson)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ContactPerson)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ContactPhone)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ContactPhone)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ItemStatus)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ItemStatus)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ProcuredBy)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ProcuredBy)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(DateProcured)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DateProcured)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(AdditionalInfo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(AdditionalInfo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Thanks)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Thanks)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(Notes)%%>', '<textarea name="Notes" id="Notes" rows="5"></textarea>', $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Donations');
	if($selected_id) {
		$jdata = get_joined_record('Donations', $selected_id);
		if($jdata === false) $jdata = get_defaults('Donations');
		$rdata = $row;
	}
	$templateCode .= loadView('Donations-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Donations_dv
	if(function_exists('Donations_dv')) {
		$args = [];
		Donations_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}