<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/OnlineReg.php');
	include_once(__DIR__ . '/OnlineReg_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('OnlineReg');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'OnlineReg';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`OnlineReg`.`Name`" => "Name",
		"`OnlineReg`.`eMail`" => "eMail",
		"`OnlineReg`.`Phone`" => "Phone",
		"`OnlineReg`.`Address1`" => "Address1",
		"`OnlineReg`.`Address2`" => "Address2",
		"`OnlineReg`.`City`" => "City",
		"`OnlineReg`.`State`" => "State",
		"`OnlineReg`.`Zip`" => "Zip",
		"`OnlineReg`.`Contry`" => "Contry",
		"`OnlineReg`.`PurchaseType`" => "PurchaseType",
		"`OnlineReg`.`IndividualDetails`" => "IndividualDetails",
		"`OnlineReg`.`TableDetails`" => "TableDetails",
		"`OnlineReg`.`Guest1`" => "Guest1",
		"`OnlineReg`.`Guest1Meal`" => "Guest1Meal",
		"`OnlineReg`.`Guest2`" => "Guest2",
		"`OnlineReg`.`Guest2Meal`" => "Guest2Meal",
		"`OnlineReg`.`Guest3`" => "Guest3",
		"`OnlineReg`.`Guest3Meal`" => "Guest3Meal",
		"`OnlineReg`.`id`" => "id",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => '`OnlineReg`.`id`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`OnlineReg`.`Name`" => "Name",
		"`OnlineReg`.`eMail`" => "eMail",
		"`OnlineReg`.`Phone`" => "Phone",
		"`OnlineReg`.`Address1`" => "Address1",
		"`OnlineReg`.`Address2`" => "Address2",
		"`OnlineReg`.`City`" => "City",
		"`OnlineReg`.`State`" => "State",
		"`OnlineReg`.`Zip`" => "Zip",
		"`OnlineReg`.`Contry`" => "Contry",
		"`OnlineReg`.`PurchaseType`" => "PurchaseType",
		"`OnlineReg`.`IndividualDetails`" => "IndividualDetails",
		"`OnlineReg`.`TableDetails`" => "TableDetails",
		"`OnlineReg`.`Guest1`" => "Guest1",
		"`OnlineReg`.`Guest1Meal`" => "Guest1Meal",
		"`OnlineReg`.`Guest2`" => "Guest2",
		"`OnlineReg`.`Guest2Meal`" => "Guest2Meal",
		"`OnlineReg`.`Guest3`" => "Guest3",
		"`OnlineReg`.`Guest3Meal`" => "Guest3Meal",
		"`OnlineReg`.`id`" => "id",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`OnlineReg`.`Name`" => "Name",
		"`OnlineReg`.`eMail`" => "EMail",
		"`OnlineReg`.`Phone`" => "Phone",
		"`OnlineReg`.`Address1`" => "Address1",
		"`OnlineReg`.`Address2`" => "Address2",
		"`OnlineReg`.`City`" => "City",
		"`OnlineReg`.`State`" => "State",
		"`OnlineReg`.`Zip`" => "Zip",
		"`OnlineReg`.`Contry`" => "Contry",
		"`OnlineReg`.`PurchaseType`" => "Purchase Type",
		"`OnlineReg`.`IndividualDetails`" => "Individual Details",
		"`OnlineReg`.`TableDetails`" => "TableDetails",
		"`OnlineReg`.`Guest1`" => "Guest 1",
		"`OnlineReg`.`Guest1Meal`" => "Guest1 Meal",
		"`OnlineReg`.`Guest2`" => "Guest 2",
		"`OnlineReg`.`Guest2Meal`" => "Guest 2 Meal",
		"`OnlineReg`.`Guest3`" => "Guest 3",
		"`OnlineReg`.`Guest3Meal`" => "Guest1 Meal",
		"`OnlineReg`.`id`" => "ID",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`OnlineReg`.`Name`" => "Name",
		"`OnlineReg`.`eMail`" => "eMail",
		"`OnlineReg`.`Phone`" => "Phone",
		"`OnlineReg`.`Address1`" => "Address1",
		"`OnlineReg`.`Address2`" => "Address2",
		"`OnlineReg`.`City`" => "City",
		"`OnlineReg`.`State`" => "State",
		"`OnlineReg`.`Zip`" => "Zip",
		"`OnlineReg`.`Contry`" => "Contry",
		"`OnlineReg`.`PurchaseType`" => "PurchaseType",
		"`OnlineReg`.`IndividualDetails`" => "IndividualDetails",
		"`OnlineReg`.`TableDetails`" => "TableDetails",
		"`OnlineReg`.`Guest1`" => "Guest1",
		"`OnlineReg`.`Guest1Meal`" => "Guest1Meal",
		"`OnlineReg`.`Guest2`" => "Guest2",
		"`OnlineReg`.`Guest2Meal`" => "Guest2Meal",
		"`OnlineReg`.`Guest3`" => "Guest3",
		"`OnlineReg`.`Guest3Meal`" => "Guest3Meal",
		"`OnlineReg`.`id`" => "id",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`OnlineReg` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'OnlineReg_view.php';
	$x->TableTitle = 'Online Registration';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`OnlineReg`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Name', 'EMail', 'Phone', 'Address1', 'Address2', 'City', 'State', 'Zip', 'Contry', 'Purchase Type', 'Individual Details', 'TableDetails', 'Guest 1', 'Guest1 Meal', 'Guest 2', 'Guest 2 Meal', 'Guest 3', 'Guest1 Meal', ];
	$x->ColFieldName = ['Name', 'eMail', 'Phone', 'Address1', 'Address2', 'City', 'State', 'Zip', 'Contry', 'PurchaseType', 'IndividualDetails', 'TableDetails', 'Guest1', 'Guest1Meal', 'Guest2', 'Guest2Meal', 'Guest3', 'Guest3Meal', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/OnlineReg_templateTV.html';
	$x->SelectedTemplate = 'templates/OnlineReg_templateTVS.html';
	$x->TemplateDV = 'templates/OnlineReg_templateDV.html';
	$x->TemplateDVP = 'templates/OnlineReg_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: OnlineReg_init
	$render = true;
	if(function_exists('OnlineReg_init')) {
		$args = [];
		$render = OnlineReg_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: OnlineReg_header
	$headerCode = '';
	if(function_exists('OnlineReg_header')) {
		$args = [];
		$headerCode = OnlineReg_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: OnlineReg_footer
	$footerCode = '';
	if(function_exists('OnlineReg_footer')) {
		$args = [];
		$footerCode = OnlineReg_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
