<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Payments.php');
	include_once(__DIR__ . '/Payments_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Payments');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Payments';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Payments`.`ID`" => "ID",
		"if(`Payments`.`Date`,date_format(`Payments`.`Date`,'%m/%d/%Y'),'')" => "Date",
		"IF(    CHAR_LENGTH(`Bidders1`.`BidNo`) || CHAR_LENGTH(`Contacts1`.`MailingNameFull`), CONCAT_WS('',   `Bidders1`.`BidNo`, ' - ', `Contacts1`.`MailingNameFull`), '') /* Bidder */" => "BidderID",
		"CONCAT('$', FORMAT(`Payments`.`PaymentAmount`, 2))" => "PaymentAmount",
		"`Payments`.`PaymentType`" => "PaymentType",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Payments`.`ID`',
		2 => '`Payments`.`Date`',
		3 => 3,
		4 => '`Payments`.`PaymentAmount`',
		5 => 5,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Payments`.`ID`" => "ID",
		"if(`Payments`.`Date`,date_format(`Payments`.`Date`,'%m/%d/%Y'),'')" => "Date",
		"IF(    CHAR_LENGTH(`Bidders1`.`BidNo`) || CHAR_LENGTH(`Contacts1`.`MailingNameFull`), CONCAT_WS('',   `Bidders1`.`BidNo`, ' - ', `Contacts1`.`MailingNameFull`), '') /* Bidder */" => "BidderID",
		"CONCAT('$', FORMAT(`Payments`.`PaymentAmount`, 2))" => "PaymentAmount",
		"`Payments`.`PaymentType`" => "PaymentType",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Payments`.`ID`" => "ID",
		"`Payments`.`Date`" => "Date",
		"IF(    CHAR_LENGTH(`Bidders1`.`BidNo`) || CHAR_LENGTH(`Contacts1`.`MailingNameFull`), CONCAT_WS('',   `Bidders1`.`BidNo`, ' - ', `Contacts1`.`MailingNameFull`), '') /* Bidder */" => "Bidder",
		"`Payments`.`PaymentAmount`" => "Payment Amount",
		"`Payments`.`PaymentType`" => "Payment Type",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Payments`.`ID`" => "ID",
		"if(`Payments`.`Date`,date_format(`Payments`.`Date`,'%m/%d/%Y'),'')" => "Date",
		"IF(    CHAR_LENGTH(`Bidders1`.`BidNo`) || CHAR_LENGTH(`Contacts1`.`MailingNameFull`), CONCAT_WS('',   `Bidders1`.`BidNo`, ' - ', `Contacts1`.`MailingNameFull`), '') /* Bidder */" => "BidderID",
		"CONCAT('$', FORMAT(`Payments`.`PaymentAmount`, 2))" => "PaymentAmount",
		"`Payments`.`PaymentType`" => "PaymentType",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['BidderID' => 'Bidder', ];

	$x->QueryFrom = "`Payments` LEFT JOIN `Bidders` as Bidders1 ON `Bidders1`.`ID`=`Payments`.`BidderID` LEFT JOIN `Contacts` as Contacts1 ON `Contacts1`.`ID`=`Bidders1`.`ContactID` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Payments_view.php';
	$x->TableTitle = 'Payments';
	$x->TableIcon = 'resources/table_icons/32Px - 385.png';
	$x->PrimaryKey = '`Payments`.`ID`';
	$x->DefaultSortField = '3';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Date', 'Bidder', 'Payment Amount', 'Payment Type', ];
	$x->ColFieldName = ['Date', 'BidderID', 'PaymentAmount', 'PaymentType', ];
	$x->ColNumber  = [2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Payments_templateTV.html';
	$x->SelectedTemplate = 'templates/Payments_templateTVS.html';
	$x->TemplateDV = 'templates/Payments_templateDV.html';
	$x->TemplateDVP = 'templates/Payments_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Payments_init
	$render = true;
	if(function_exists('Payments_init')) {
		$args = [];
		$render = Payments_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// column sums
	if(strpos($x->HTML, '<!-- tv data below -->')) {
		// if printing multi-selection TV, calculate the sum only for the selected records
		$record_selector = Request::val('record_selector');
		if(Request::val('Print_x') && is_array($record_selector)) {
			$QueryWhere = '';
			foreach($record_selector as $id) {   // get selected records
				if($id != '') $QueryWhere .= "'" . makeSafe($id) . "',";
			}
			if($QueryWhere != '') {
				$QueryWhere = 'where `Payments`.`ID` in ('.substr($QueryWhere, 0, -1).')';
			} else { // if no selected records, write the where clause to return an empty result
				$QueryWhere = 'where 1=0';
			}
		} else {
			$QueryWhere = $x->QueryWhere;
		}

		$sumQuery = "SELECT CONCAT('$', FORMAT(SUM(`Payments`.`PaymentAmount`), 2)) FROM {$x->QueryFrom} {$QueryWhere}";
		$res = sql($sumQuery, $eo);
		if($row = db_fetch_row($res)) {
			$sumRow = '<tr class="success sum">';
			if(!Request::val('Print_x')) $sumRow .= '<th class="text-center sum">&sum;</th>';
			$sumRow .= '<td class="Payments-Date sum"></td>';
			$sumRow .= '<td class="Payments-BidderID sum"></td>';
			$sumRow .= "<td class=\"Payments-PaymentAmount text-right sum locale-float\">{$row[0]}</td>";
			$sumRow .= '<td class="Payments-PaymentType sum"></td>';
			$sumRow .= '</tr>';

			$x->HTML = str_replace('<!-- tv data below -->', '', $x->HTML);
			$x->HTML = str_replace('<!-- tv data above -->', $sumRow, $x->HTML);
		}
	}

	// hook: Payments_header
	$headerCode = '';
	if(function_exists('Payments_header')) {
		$args = [];
		$headerCode = Payments_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Payments_footer
	$footerCode = '';
	if(function_exists('Payments_footer')) {
		$args = [];
		$footerCode = Payments_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
