<?php

// Data functions (insert, update, delete, form) for table Settings

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function Settings_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Settings');
	if(!$arrPerm['insert']) return false;

	$data = [
		'EventName' => Request::val('EventName', ''),
		'EventDate' => Request::val('EventDate', ''),
		'AnonymousName' => Request::val('AnonymousName', ''),
		'Address' => br2nl(Request::val('Address', '')),
		'RegTicketPrice' => Request::val('RegTicketPrice', ''),
		'DiscTicketPrice' => Request::val('DiscTicketPrice', ''),
		'DinnerCost' => Request::val('DinnerCost', ''),
		'Logo' => Request::fileUpload('Logo', [
			'maxSize' => 512000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => true,
			'dir' => '',
			'success' => function($name, $selected_id) {
				createThumbnail($name, getThumbnailSpecs('Settings', 'Logo', 'tv'));
				createThumbnail($name, getThumbnailSpecs('Settings', 'Logo', 'dv'));
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('Settings', 'Logo', Request::val('SelectedID'));
			},
		]),
	];


	// hook: Settings_before_insert
	if(function_exists('Settings_before_insert')) {
		$args = [];
		if(!Settings_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Settings', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Settings', $recID, calculated_fields()['Settings']);

	// hook: Settings_after_insert
	if(function_exists('Settings_after_insert')) {
		$res = sql("SELECT * FROM `Settings` WHERE `ID`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Settings_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	// record owner is current user
	$recordOwner = getLoggedMemberID();
	set_record_owner('Settings', $recID, $recordOwner);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Settings_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Settings_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Settings_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Settings', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Settings_before_delete
	if(function_exists('Settings_before_delete')) {
		$args = [];
		if(!Settings_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// delete file stored in the 'Logo' field
	$res = sql("SELECT `Logo` FROM `Settings` WHERE `ID`='{$selected_id}'", $eo);
	if($row = @db_fetch_row($res)) {
		if($row[0] != '') {
			@unlink(getUploadDir('') . $row[0]);
			$thumbDV = preg_replace('/\.(jpg|jpeg|gif|png|webp)$/i', '_dv.$1', $row[0]);
			$thumbTV = preg_replace('/\.(jpg|jpeg|gif|png|webp)$/i', '_tv.$1', $row[0]);
			@unlink(getUploadDir('') . $thumbTV);
			@unlink(getUploadDir('') . $thumbDV);
		}
	}

	sql("DELETE FROM `Settings` WHERE `ID`='{$selected_id}'", $eo);

	// hook: Settings_after_delete
	if(function_exists('Settings_after_delete')) {
		$args = [];
		Settings_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Settings' AND `pkValue`='{$selected_id}'", $eo);
}

function Settings_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Settings', $selected_id, 'edit')) return false;

	$data = [
		'EventName' => Request::val('EventName', ''),
		'EventDate' => Request::val('EventDate', ''),
		'AnonymousName' => Request::val('AnonymousName', ''),
		'Address' => br2nl(Request::val('Address', '')),
		'RegTicketPrice' => Request::val('RegTicketPrice', ''),
		'DiscTicketPrice' => Request::val('DiscTicketPrice', ''),
		'DinnerCost' => Request::val('DinnerCost', ''),
		'Logo' => Request::fileUpload('Logo', [
			'maxSize' => 512000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => true,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
				createThumbnail($name, getThumbnailSpecs('Settings', 'Logo', 'tv'));
				createThumbnail($name, getThumbnailSpecs('Settings', 'Logo', 'dv'));
			},
			'removeOnSuccess' => true,
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// delete old file from server
				$oldFile = existing_value('Settings', 'Logo', $selected_id);
				if(!$oldFile) return;

				@unlink(getUploadDir('') . $oldFile);

				// delete thumbnails
				preg_match('/^[a-z0-9_]+\.(jpg|jpeg|gif|png|webp)$/i', $oldFile, $m);
				$thumbDV = str_replace(".{$m[1]}ffffgggg", "_dv.{$m[1]}", $oldFile . 'ffffgggg');
				$thumbTV = str_replace(".{$m[1]}ffffgggg", "_tv.{$m[1]}", $oldFile . 'ffffgggg');
				@unlink(getUploadDir('') . $thumbTV);
				@unlink(getUploadDir('') . $thumbDV);
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('Settings', 'Logo', $selected_id);
			},
		]),
	];

	// get existing values
	$old_data = getRecord('Settings', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Settings_before_update
	if(function_exists('Settings_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Settings_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Settings', 
		backtick_keys_once($set), 
		['`ID`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Settings_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Settings', $data['selectedID'], calculated_fields()['Settings']);

	// hook: Settings_after_update
	if(function_exists('Settings_after_update')) {
		$res = sql("SELECT * FROM `Settings` WHERE `ID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['ID'];
		$args = ['old_data' => $old_data];
		if(!Settings_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('Settings', $selected_id);
}

function Settings_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Settings');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($selected_id) {
		if(!check_record_permission('Settings', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('Settings', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('Settings', $selected_id, 'delete');

		$res = sql("SELECT * FROM `Settings` WHERE `ID`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Settings_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Settings_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Settings_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Setting details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Settings_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Settings_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Settings_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#EventName').replaceWith('<div class=\"form-control-static\" id=\"EventName\">' + (jQuery('#EventName').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#EventDate').replaceWith('<div class=\"form-control-static\" id=\"EventDate\">' + (jQuery('#EventDate').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#AnonymousName').replaceWith('<div class=\"form-control-static\" id=\"AnonymousName\">' + (jQuery('#AnonymousName').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Address').replaceWith('<div class=\"form-control-static\" id=\"Address\">' + (jQuery('#Address').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#RegTicketPrice').replaceWith('<div class=\"form-control-static\" id=\"RegTicketPrice\">' + (jQuery('#RegTicketPrice').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#DiscTicketPrice').replaceWith('<div class=\"form-control-static\" id=\"DiscTicketPrice\">' + (jQuery('#DiscTicketPrice').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#DinnerCost').replaceWith('<div class=\"form-control-static\" id=\"DinnerCost\">' + (jQuery('#DinnerCost').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Logo').replaceWith('<div class=\"form-control-static\" id=\"Logo\">' + (jQuery('#Logo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(ID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(EventName)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(EventDate)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(AnonymousName)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Address)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(RegTicketPrice)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(DiscTicketPrice)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(DinnerCost)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Logo)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<input type="file" name="Logo" id="Logo" data-filetypes="jpg|jpeg|gif|png|webp" data-maxsize="512000" style="max-width: calc(100% - 1.5rem);" accept="capture=camera,image/*">' . '<i class="text-danger clear-upload hidden pull-right" style="margin-top: -.1em; font-size: large;">&times;</i>'), $templateCode);
	if($AllowUpdate && $row['Logo'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(Logo)%%>', '<input type="checkbox" name="Logo_remove" id="Logo_remove" value="1"> <label for="Logo_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(Logo)%%>', '', $templateCode);
	}

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ID)%%>', safe_html($urow['ID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ID)%%>', html_attr($row['ID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ID)%%>', urlencode($urow['ID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(EventName)%%>', safe_html($urow['EventName']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(EventName)%%>', html_attr($row['EventName']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(EventName)%%>', urlencode($urow['EventName']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(EventDate)%%>', safe_html($urow['EventDate']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(EventDate)%%>', html_attr($row['EventDate']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(EventDate)%%>', urlencode($urow['EventDate']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(AnonymousName)%%>', safe_html($urow['AnonymousName']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(AnonymousName)%%>', html_attr($row['AnonymousName']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(AnonymousName)%%>', urlencode($urow['AnonymousName']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(Address)%%>', safe_html($urow['Address']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(Address)%%>', safe_html($urow['Address'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(Address)%%>', urlencode($urow['Address']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(RegTicketPrice)%%>', safe_html($urow['RegTicketPrice']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(RegTicketPrice)%%>', html_attr($row['RegTicketPrice']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(RegTicketPrice)%%>', urlencode($urow['RegTicketPrice']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(DiscTicketPrice)%%>', safe_html($urow['DiscTicketPrice']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(DiscTicketPrice)%%>', html_attr($row['DiscTicketPrice']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DiscTicketPrice)%%>', urlencode($urow['DiscTicketPrice']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(DinnerCost)%%>', safe_html($urow['DinnerCost']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(DinnerCost)%%>', html_attr($row['DinnerCost']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DinnerCost)%%>', urlencode($urow['DinnerCost']), $templateCode);
		$row['Logo'] = ($row['Logo'] != '' ? $row['Logo'] : 'blank.gif');
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Logo)%%>', safe_html($urow['Logo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Logo)%%>', html_attr($row['Logo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Logo)%%>', urlencode($urow['Logo']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(ID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(EventName)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(EventName)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(EventDate)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(EventDate)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(AnonymousName)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(AnonymousName)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Address)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Address)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(RegTicketPrice)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(RegTicketPrice)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(DiscTicketPrice)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DiscTicketPrice)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(DinnerCost)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DinnerCost)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Logo)%%>', 'blank.gif', $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Settings');
	if($selected_id) {
		$jdata = get_joined_record('Settings', $selected_id);
		if($jdata === false) $jdata = get_defaults('Settings');
		$rdata = $row;
	}
	$templateCode .= loadView('Settings-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Settings_dv
	if(function_exists('Settings_dv')) {
		$args = [];
		Settings_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}