<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Tables.php');
	include_once(__DIR__ . '/Tables_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Tables');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Tables';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Tables`.`ID`" => "ID",
		"`Tables`.`TableNo`" => "TableNo",
		"`Tables`.`TableName`" => "TableName",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Tables`.`ID`',
		2 => 2,
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Tables`.`ID`" => "ID",
		"`Tables`.`TableNo`" => "TableNo",
		"`Tables`.`TableName`" => "TableName",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Tables`.`ID`" => "ID",
		"`Tables`.`TableNo`" => "TableNo",
		"`Tables`.`TableName`" => "TableName",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Tables`.`ID`" => "ID",
		"`Tables`.`TableNo`" => "TableNo",
		"`Tables`.`TableName`" => "TableName",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`Tables` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Tables_view.php';
	$x->TableTitle = 'Tables';
	$x->TableIcon = 'resources/table_icons/32Px - 112.png';
	$x->PrimaryKey = '`Tables`.`ID`';
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, 150, 100, ];
	$x->ColCaption = ['TableNo', 'TableName', 'Tickets', ];
	$x->ColFieldName = ['TableNo', 'TableName', '%Tickets.TableID%', ];
	$x->ColNumber  = [2, 3, -1, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Tables_templateTV.html';
	$x->SelectedTemplate = 'templates/Tables_templateTVS.html';
	$x->TemplateDV = 'templates/Tables_templateDV.html';
	$x->TemplateDVP = 'templates/Tables_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Tables_init
	$render = true;
	if(function_exists('Tables_init')) {
		$args = [];
		$render = Tables_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Tables_header
	$headerCode = '';
	if(function_exists('Tables_header')) {
		$args = [];
		$headerCode = Tables_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Tables_footer
	$footerCode = '';
	if(function_exists('Tables_footer')) {
		$args = [];
		$footerCode = Tables_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
