<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Transactions.php');
	include_once(__DIR__ . '/Transactions_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Transactions');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Transactions';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Transactions`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`Catalog1`.`CatalogNo`) || CHAR_LENGTH(`Catalog1`.`CatalogTitle`), CONCAT_WS('',   `Catalog1`.`CatalogNo`, ' - ', `Catalog1`.`CatalogTitle`), '') /* Catalog # */" => "CatalogID",
		"IF(    CHAR_LENGTH(`Bidders1`.`BidNo`) || CHAR_LENGTH(`Contacts1`.`MailingNameFull`), CONCAT_WS('',   `Bidders1`.`BidNo`, ' - ', `Contacts1`.`MailingNameFull`), '') /* Bidder */" => "BidderID",
		"`Transactions`.`Price`" => "Price",
		"`Transactions`.`Quantity`" => "Quantity",
		"`Transactions`.`Total`" => "Total",
		"IF(    CHAR_LENGTH(`Catalog1`.`Values`), CONCAT_WS('',   `Catalog1`.`Values`), '') /* Catalog Value */" => "CatValue",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Transactions`.`ID`',
		2 => 2,
		3 => 3,
		4 => '`Transactions`.`Price`',
		5 => '`Transactions`.`Quantity`',
		6 => '`Transactions`.`Total`',
		7 => '`Catalog1`.`Values`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Transactions`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`Catalog1`.`CatalogNo`) || CHAR_LENGTH(`Catalog1`.`CatalogTitle`), CONCAT_WS('',   `Catalog1`.`CatalogNo`, ' - ', `Catalog1`.`CatalogTitle`), '') /* Catalog # */" => "CatalogID",
		"IF(    CHAR_LENGTH(`Bidders1`.`BidNo`) || CHAR_LENGTH(`Contacts1`.`MailingNameFull`), CONCAT_WS('',   `Bidders1`.`BidNo`, ' - ', `Contacts1`.`MailingNameFull`), '') /* Bidder */" => "BidderID",
		"`Transactions`.`Price`" => "Price",
		"`Transactions`.`Quantity`" => "Quantity",
		"`Transactions`.`Total`" => "Total",
		"IF(    CHAR_LENGTH(`Catalog1`.`Values`), CONCAT_WS('',   `Catalog1`.`Values`), '') /* Catalog Value */" => "CatValue",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Transactions`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`Catalog1`.`CatalogNo`) || CHAR_LENGTH(`Catalog1`.`CatalogTitle`), CONCAT_WS('',   `Catalog1`.`CatalogNo`, ' - ', `Catalog1`.`CatalogTitle`), '') /* Catalog # */" => "Catalog #",
		"IF(    CHAR_LENGTH(`Bidders1`.`BidNo`) || CHAR_LENGTH(`Contacts1`.`MailingNameFull`), CONCAT_WS('',   `Bidders1`.`BidNo`, ' - ', `Contacts1`.`MailingNameFull`), '') /* Bidder */" => "Bidder",
		"`Transactions`.`Price`" => "Price",
		"`Transactions`.`Quantity`" => "Quantity",
		"`Transactions`.`Total`" => "Total",
		"IF(    CHAR_LENGTH(`Catalog1`.`Values`), CONCAT_WS('',   `Catalog1`.`Values`), '') /* Catalog Value */" => "Catalog Value",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Transactions`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`Catalog1`.`CatalogNo`) || CHAR_LENGTH(`Catalog1`.`CatalogTitle`), CONCAT_WS('',   `Catalog1`.`CatalogNo`, ' - ', `Catalog1`.`CatalogTitle`), '') /* Catalog # */" => "CatalogID",
		"IF(    CHAR_LENGTH(`Bidders1`.`BidNo`) || CHAR_LENGTH(`Contacts1`.`MailingNameFull`), CONCAT_WS('',   `Bidders1`.`BidNo`, ' - ', `Contacts1`.`MailingNameFull`), '') /* Bidder */" => "BidderID",
		"`Transactions`.`Price`" => "Price",
		"`Transactions`.`Quantity`" => "Quantity",
		"`Transactions`.`Total`" => "Total",
		"IF(    CHAR_LENGTH(`Catalog1`.`Values`), CONCAT_WS('',   `Catalog1`.`Values`), '') /* Catalog Value */" => "CatValue",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['CatalogID' => 'Catalog #', 'BidderID' => 'Bidder', ];

	$x->QueryFrom = "`Transactions` LEFT JOIN `Catalog` as Catalog1 ON `Catalog1`.`ID`=`Transactions`.`CatalogID` LEFT JOIN `Bidders` as Bidders1 ON `Bidders1`.`ID`=`Transactions`.`BidderID` LEFT JOIN `Contacts` as Contacts1 ON `Contacts1`.`ID`=`Bidders1`.`ContactID` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Transactions_view.php';
	$x->TableTitle = 'Transactions';
	$x->TableIcon = 'resources/table_icons/32Px - 397.png';
	$x->PrimaryKey = '`Transactions`.`ID`';

	$x->ColWidth = [150, 150, 80, 150, 150, 150, ];
	$x->ColCaption = ['Catalog #', 'Bidder', 'Price', 'Quantity', 'Total', 'Catalog Value', ];
	$x->ColFieldName = ['CatalogID', 'BidderID', 'Price', 'Quantity', 'Total', 'CatValue', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Transactions_templateTV.html';
	$x->SelectedTemplate = 'templates/Transactions_templateTVS.html';
	$x->TemplateDV = 'templates/Transactions_templateDV.html';
	$x->TemplateDVP = 'templates/Transactions_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Transactions_init
	$render = true;
	if(function_exists('Transactions_init')) {
		$args = [];
		$render = Transactions_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Transactions_header
	$headerCode = '';
	if(function_exists('Transactions_header')) {
		$args = [];
		$headerCode = Transactions_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Transactions_footer
	$footerCode = '';
	if(function_exists('Transactions_footer')) {
		$args = [];
		$footerCode = Transactions_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
